version: '3'
services:
    web:
        build:
            context: ./app
            dockerfile: docker/Dockerfile
        volumes:
            - ./app:/django/
        restart: always
        ports:
            - "80:8000"
        networks:
            sail:
                ipv4_address: 172.25.0.2
    pgsql:
        image: 'postgres:15'
        restart: always
        environment:
            POSTGRES_DB: '${POSTGRES_DB}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
        volumes:
            - ./database/pgsql:/var/lib/postgresql/data
        networks:
            sail:
                ipv4_address: 172.25.0.3
networks:
    sail:
        driver: bridge
        ipam:
            config:
                -   subnet: 172.25.0.0/16
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local