# Generated by Django 4.2.1 on 2023-05-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photos', models.JSONField()),
                ('seconds_time', models.IntegerField()),
                ('count_calories', models.IntegerField()),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('points', models.IntegerField(default=10)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apiuser')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='users',
            field=models.ManyToManyField(through='users.ExerciseUser', to='users.apiuser'),
        ),
    ]
